#!/usr/bin/env bash
# sync-upstream-titles.sh — extract upstream kickstart section titles,
# compare against scripts/upstream-map.tsv, regenerate UPSTREAM_SYNC.md,
# and flag drift (titles added/removed in upstream vs. the map).
#
# Usage:
#   scripts/sync-upstream-titles.sh          # regenerate + report drift
#   scripts/sync-upstream-titles.sh --check  # report only, exit non-zero on drift
#
# Edit scripts/upstream-map.tsv to update mappings; do not edit UPSTREAM_SYNC.md directly.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
map_file="$repo_root/scripts/upstream-map.tsv"
out_file="$repo_root/UPSTREAM_SYNC.md"
check_only=0

if [[ "${1:-}" == "--check" ]]; then
  check_only=1
fi

# Guard: upstream branch must exist locally
if ! git -C "$repo_root" rev-parse --verify upstream >/dev/null 2>&1; then
  echo "Error: local branch 'upstream' not found. Fetch it first." >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# 1. Extract upstream titles
# ---------------------------------------------------------------------------

# Section titles from init.lua (strip leading whitespace and [[ ]] delimiters)
init_titles_with_lines="$(
  git -C "$repo_root" show upstream:init.lua \
    | grep -n -E '^\s*--\s*\[\[.*\]\]' \
    | sed 's/^\([0-9]*\):.*\[\[\(.*\)\]\].*/\1\t\2/' \
    | sed 's/\t /\t/; s/ $//'
)"
# e.g. lines like: "104\tSetting options"

# Plugin module names from lua/kickstart/plugins/
plugin_titles="$(
  git -C "$repo_root" ls-tree -r --name-only upstream -- lua/kickstart/plugins/ \
    | sed 's|lua/kickstart/plugins/\(.*\)\.lua|plugins:\1|' \
    | sort
)"

# All upstream titles (plain, no line info) for drift comparison
upstream_init_titles="$(echo "$init_titles_with_lines" | awk -F'\t' '{print $2}')"
upstream_all_titles="$(printf '%s\n%s\n' "$upstream_init_titles" "$plugin_titles")"

# ---------------------------------------------------------------------------
# 2. Read the TSV map (skip header)
# ---------------------------------------------------------------------------

# map_titles: column 1 of the TSV (upstream_title)
map_titles="$(awk -F'\t' 'NR>1 {print $1}' "$map_file")"

# ---------------------------------------------------------------------------
# 3. Drift detection
# ---------------------------------------------------------------------------

# NEW: in upstream but not in map
new_titles="$(comm -23 \
  <(echo "$upstream_all_titles" | sort) \
  <(echo "$map_titles" | sort))"

# REMOVED: in map but not in upstream
removed_titles="$(comm -23 \
  <(echo "$map_titles" | sort) \
  <(echo "$upstream_all_titles" | sort))"

# ---------------------------------------------------------------------------
# 4. Print drift report (always, regardless of --check)
# ---------------------------------------------------------------------------

echo "=== Upstream title drift ==="
drift=0

if [[ -n "$new_titles" ]]; then
  drift=1
  while IFS= read -r title; do
    echo "NEW (not in map):   $title"
  done <<< "$new_titles"
fi

if [[ -n "$removed_titles" ]]; then
  drift=1
  while IFS= read -r title; do
    echo "REMOVED (not in upstream): $title"
  done <<< "$removed_titles"
fi

if [[ $drift -eq 0 ]]; then
  echo "No drift detected."
fi

# ---------------------------------------------------------------------------
# 5. Regenerate UPSTREAM_SYNC.md (unless --check)
# ---------------------------------------------------------------------------

if [[ $check_only -eq 0 ]]; then
  # Build table rows: init.lua sections first (in file order), then plugins: (sorted)
  {
    echo "<!-- Generated by scripts/sync-upstream-titles.sh — edit scripts/upstream-map.tsv, not this file -->"
    echo ""
    echo "# Upstream Sync Map"
    echo ""
    echo "| Upstream title | Upstream source | Fork module | Notes |"
    echo "|---|---|---|---|"

    # init.lua rows — iterate in file order (already ordered by line number)
    while IFS=$'\t' read -r linenum title; do
      # Look up fork_module and notes from the map
      fork_module="$(awk -F'\t' -v t="$title" 'NR>1 && $1==t {print $2; exit}' "$map_file")"
      notes="$(awk -F'\t' -v t="$title" 'NR>1 && $1==t {print $3; exit}' "$map_file")"
      echo "| $title | \`init.lua:$linenum\` | \`$fork_module\` | $notes |"
    done <<< "$init_titles_with_lines"

    # plugins: rows — sorted
    while IFS= read -r title; do
      [[ -z "$title" ]] && continue
      plugin_name="${title#plugins:}"
      source_path="lua/kickstart/plugins/${plugin_name}.lua"
      fork_module="$(awk -F'\t' -v t="$title" 'NR>1 && $1==t {print $2; exit}' "$map_file")"
      notes="$(awk -F'\t' -v t="$title" 'NR>1 && $1==t {print $3; exit}' "$map_file")"
      echo "| $title | \`$source_path\` | \`$fork_module\` | $notes |"
    done <<< "$plugin_titles"

  } > "$out_file"

  echo "Written: $out_file"
fi

# ---------------------------------------------------------------------------
# 6. Exit code
# ---------------------------------------------------------------------------

exit $drift
